### ISSUE TITLE
Sitemap generate command does not generate with site URL

### ISSUE THREAD

**Issue by JABirchall** [blendinteractive/ez-sitemap-bundle#7]
When generating a sitemap with the controller it passed through the main_url for twig to build the full URL in the sitemap, how ever for sake of resources we are using the command on a cron and noticed the sitemap does not contain the full URL, only the paths.

This make the sitemap invalid and search engines can not find content on your site.

**Comment by JABirchall** [comment]
This issue is resolved by PR #8 by preappending the hostname on generation

**Comment by harmstyler** [comment]
Thanks for the PR.
